In [1]:
import pandas as pd
import numpy as np

In [12]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
'key2' : ['one', 'two', 'one', 'two', 'one'],
'data1' : np.random.randn(5),
'data2' : np.random.randn(5)})

## Group by

In [13]:
df

  key1 key2     data1     data2
0    a  one  0.937820 -0.721657
1    a  two -0.723659  0.367691
2    b  one  0.094167  0.277840
3    b  two  2.243301 -0.564709
4    a  one  0.537321 -0.874237

In [18]:
grouped = df.groupby(df['key1'])

In [19]:
grouped

In [20]:
grouped.mean()

         data1     data2
key1
a     0.250494 -0.409401
b     1.168734 -0.143434

# Mas de un índice

In [23]:
means = df.groupby([df['key1'], df['key2']]).mean()

In [24]:
means

              data1     data2
key1 key2
a    one   0.737570 -0.797947
     two  -0.723659  0.367691
b    one   0.094167  0.277840
     two   2.243301 -0.564709

In [26]:
df

  key1 key2     data1     data2
0    a  one  0.937820 -0.721657
1    a  two -0.723659  0.367691
2    b  one  0.094167  0.277840
3    b  two  2.243301 -0.564709
4    a  one  0.537321 -0.874237

In [25]:
df['data1'].groupby([df['key1'], df['key2']]).aggregate(np.std)

key1  key2
a     one     0.283196
      two          NaN
b     one          NaN
      two          NaN
Name: data1, dtype: float64

# Pivot

In [2]:
# importing pandas as pd
import pandas as pd
  
# creating a dataframe
df = pd.DataFrame({'A': ['John', 'Boby', 'Mina'],
      'B': ['Masters', 'Graduate', 'Graduate'],
      'C': [27, 23, 21]})

In [3]:
df

      A         B   C
0  John   Masters  27
1  Boby  Graduate  23
2  Mina  Graduate  21

In [4]:
df.pivot(columns='B')

         A                C
B Graduate Masters Graduate Masters
0      NaN    John      NaN    27.0
1     Boby     NaN     23.0     NaN
2     Mina     NaN     21.0     NaN

In [5]:
df.pivot(index ='A', columns ='B', values =['C'])

            C
B    Graduate Masters
A
Boby     23.0     NaN
John      NaN    27.0
Mina     21.0     NaN

In [7]:
dfp = df.pivot(index ='A', columns ='B', values =['C', 'A'])

In [8]:
dfp.head()

            C                A
B    Graduate Masters Graduate Masters
A
Boby       23     NaN     Boby     NaN
John      NaN      27      NaN    John
Mina       21     NaN     Mina     NaN

In [9]:
df1 = pd.DataFrame({'A': ['John', 'John', 'Mina'],
      'B': ['Masters', 'Masters', 'Graduate'],
      'C': [27, 23, 21]})

In [10]:
df1

      A         B   C
0  John   Masters  27
1  John   Masters  23
2  Mina  Graduate  21

In [11]:
df1.pivot(index='A',columns= 'B',values= ['C'])

ValueError: ignored